# SIMULATION
DEFAULT_MAX_STEPS = 200
DEFAULT_MAX_ERRORS = 10
DEFAULT_SEED = 300
DEFAULT_MAX_CONCURRENCY = 3
DEFAULT_NUM_TRIALS = 1
DEFAULT_SAVE_TO = None
DEFAULT_LOG_LEVEL = "ERROR"

# LLM
DEFAULT_AGENT_IMPLEMENTATION = "llm_agent"
DEFAULT_USER_IMPLEMENTATION = "user_simulator"
DEFAULT_LLM_AGENT = "gpt-4.1"
DEFAULT_LLM_USER = "gpt-4.1"
DEFAULT_LLM_TEMPERATURE_AGENT = 0.0
DEFAULT_LLM_TEMPERATURE_USER = 0.0
DEFAULT_LLM_ARGS_AGENT = {"temperature": DEFAULT_LLM_TEMPERATURE_AGENT}
DEFAULT_LLM_ARGS_USER = {"temperature": DEFAULT_LLM_TEMPERATURE_USER}

DEFAULT_LLM_NL_ASSERTIONS = "gpt-4o-mini"
DEFAULT_LLM_NL_ASSERTIONS_TEMPERATURE = 0.0
DEFAULT_LLM_NL_ASSERTIONS_ARGS = {"temperature": DEFAULT_LLM_NL_ASSERTIONS_TEMPERATURE}

DEFAULT_LLM_ENV_INTERFACE = "gpt-4.1"
DEFAULT_LLM_ENV_INTERFACE_TEMPERATURE = 0.0
DEFAULT_LLM_ENV_INTERFACE_ARGS = {"temperature": DEFAULT_LLM_ENV_INTERFACE_TEMPERATURE}

# LITELLM
DEFAULT_MAX_RETRIES = 3
LLM_CACHE_ENABLED = False
DEFAULT_LLM_CACHE_TYPE = "redis"

# REDIS CACHE
REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_PASSWORD = ""
REDIS_PREFIX = "siva"
REDIS_CACHE_VERSION = "v1"
REDIS_CACHE_TTL = 60 * 60 * 24 * 30

# LANGFUSE
USE_LANGFUSE = False  # If True, make sure all the env variables are set for langfuse.

# API
API_PORT = 8000

# SIVA-SPECIFIC CONFIGURATION
# API Keys
OPENAI_API_KEY = None  # Will be loaded from environment
CARTESIA_API_KEY = None  # Will be loaded from environment

# FastAPI Configuration
APP_HOST = "localhost"
APP_PORT = 8000
APP_RELOAD = True
APP_DEBUG = False

# Client Server Configuration
CLIENT_HOST = "localhost"
CLIENT_PORT = 3000

# Vector Store Configuration
RETRIEVAL_THRESHOLD = 3
SIMILARITY_THRESHOLD = 0.75

# Voice Configuration
SONIC_MODEL_ID = "sonic-2"
VOICE_ID = "5c43e078-5ba4-4e1f-9639-8d85a403f76a"

# Data Storage Configuration
DATA_DIR = "siva_data"

# OpenAI Configuration
OPENAI_MODEL = "gpt-3.5-turbo-1106"
OPENAI_EMBEDDING_MODEL = "text-embedding-3-small"
OPENAI_WHISPER_MODEL = "whisper-1"
OPENAI_MAX_TOKENS = 300
OPENAI_TEMPERATURE = 0.3

# Application Mode
CURRENT_MODE = "patient_intake"

# CORS Configuration
CORS_ORIGINS = ["*"]
CORS_CREDENTIALS = True
CORS_METHODS = ["*"]
CORS_HEADERS = ["*"]
